### ISSUE TITLE
Allow loading Model, Optimizer, and Scheduler Training Checkpoints from Hugging Face

### ISSUE THREAD

**Issue by ramppdev** [autrainer/autrainer#134]
Right now a model can specify a `model_checkpoint`, `optimizer_checkpoint`, and `scheduler_checkpoint` from a local path.
For `autrainer inference` we support loading models from Hugging Face in combination with a checkpoint.

This functionality could be added to the model, optimizer, and scheduler checkpoints used for training as well, by also allowing the user to pass sth like:
```yaml
# conf/model/SomeModel.yaml
id: SomeModel
...

model_checkpoint: hf:repo_id[@revision][:subdir]#local_dir
# or 
model_checkpoint:
    link: hf:repo_id[@revision][:subdir]#local_dir
    checkpoint: best # best, last, epoch / iteration number, defaults to best
```
