### ISSUE TITLE
Torchvision model transforms missing

### ISSUE THREAD

**Issue by ATriantafyllopoulos** [autrainer/autrainer#75]
If I compare [the original AlexNet](https://pytorch.org/vision/main/models/generated/torchvision.models.alexnet.html) with [our configuration](https://github.com/autrainer/autrainer/blob/main/autrainer-configurations/model/AlexNet-T.yaml), it appears like we are completely missing the transforms that are mentioned. This is also true for all other `torchvision` models.

This could lead to serious problems with the models as we give them a vastly different input space.

I will investigate and upgrade to a bug if this is indeed missing.

**Comment by ATriantafyllopoulos** [comment]
Adding the following seems to substantially improve model performance on some local data (basically going from NaNs to modest performance comparable to the state of the art).

```yaml
id: AlexNet-T-v2
_target_: autrainer.models.TorchvisionModel
torchvision_name: alexnet
transfer: true

transform:
  type: image
  base:
    - autrainer.transforms.Resize:
        height: 224
        width: 224
    - autrainer.transforms.ScaleRange:
      order: 90
    - autrainer.transforms.Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
```

I might be missing something here because there are some stuff happening under-the-hood with this [match model dataset stuff](https://github.com/autrainer/autrainer/blob/68b19a83061f99988dc4a20d6c4aece9911acd58/autrainer/transforms/transform_manager.py#L190)

@ramppdev @millinma do you have any insights?
